#!/bin/bash
# bridges/cc-connect.sh — cc-connect chat bridge.
#
# Multi-platform chat bridge for Claude Code / Studio Code. No per-install
# config artifacts beyond the npm package + a user-owned config.toml. Token
# is optional; the bridge runs without one.

# ============================================================================
# Identity
# ============================================================================

bridge_systemd_units()  { echo "cc-connect.service"; }
bridge_launchd_labels() { echo "com.wp.cc-connect"; }
bridge_binaries()       { echo "cc-connect"; }
bridge_display_name()   { echo "cc-connect"; }
bridge_display_title()  { echo "cc-connect"; }

# cc-connect has no token requirement — always ready to start.
bridge_is_ready() { return 0; }

# ============================================================================
# Install (setup-time)
# ============================================================================

bridge_install() {
  if ! command -v cc-connect &> /dev/null || [ "$DRY_RUN" = true ]; then
    run_cmd npm install -g cc-connect
  else
    log "cc-connect already installed"
  fi

  CC_DATA_DIR="${CC_DATA_DIR:-$SERVICE_HOME/.cc-connect}"

  if [ "$LOCAL_MODE" = true ] && [ "$PLATFORM" = "mac" ]; then
    _cc_connect_install_launchd
  elif [ "$LOCAL_MODE" = true ]; then
    run_cmd mkdir -p "$CC_DATA_DIR"
    _cc_connect_write_config
    log "Local mode: cc-connect installed. Run manually with:"
    log "  cd $SITE_PATH && cc-connect"
  else
    _cc_connect_install_systemd
  fi
}

_cc_connect_write_config() {
  CC_CONFIG_FILE="$CC_DATA_DIR/config.toml"
  if [ "$DRY_RUN" = false ] && [ -f "$CC_CONFIG_FILE" ]; then
    log "cc-connect config already exists — skipping"
    return
  fi

  CC_CONFIG="# cc-connect configuration
# Generated by wp-coding-agents setup

[project]
path = \"$SITE_PATH\"
agent = \"claude\"

[claude]
working_directory = \"$SITE_PATH\""

  write_file "$CC_CONFIG_FILE" "$CC_CONFIG"
  log "Generated cc-connect config at $CC_CONFIG_FILE"
}

_cc_connect_install_launchd() {
  CC_PLIST_LABEL="com.wp.cc-connect"
  CC_PLIST_DIR="$HOME/Library/LaunchAgents"
  CC_PLIST="$CC_PLIST_DIR/$CC_PLIST_LABEL.plist"

  if [ "$DRY_RUN" = true ]; then
    CC_BIN="/opt/homebrew/bin/cc-connect"
  else
    CC_BIN=$(which cc-connect 2>/dev/null || echo "/opt/homebrew/bin/cc-connect")
  fi

  run_cmd mkdir -p "$CC_DATA_DIR"
  run_cmd mkdir -p "$CC_PLIST_DIR"
  _cc_connect_write_config

  write_file "$CC_PLIST" "$(bridge_render_launchd "$CC_PLIST_LABEL")"

  if [ "$DRY_RUN" = false ]; then
    launchctl bootout "gui/$(id -u)" "$CC_PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$CC_PLIST"
    log "cc-connect launchd service installed and loaded"
  fi

  log "cc-connect service: $CC_PLIST_LABEL"
  log "  Start:  launchctl kickstart gui/$(id -u)/$CC_PLIST_LABEL"
  log "  Stop:   launchctl kill SIGTERM gui/$(id -u)/$CC_PLIST_LABEL"
  log "  Logs:   tail -f $CC_DATA_DIR/cc-connect.log"
}

_cc_connect_install_systemd() {
  run_cmd mkdir -p "$CC_DATA_DIR"
  _cc_connect_write_config

  local ENV_BLOCK="Environment=HOME=$SERVICE_HOME
Environment=PATH=/usr/local/bin:/usr/bin:/bin"
  if [ -n "${CC_CONNECT_TOKEN:-}" ]; then
    ENV_BLOCK="$ENV_BLOCK
Environment=CC_CONNECT_TOKEN=$CC_CONNECT_TOKEN"
  fi

  if [ "$DRY_RUN" = true ]; then
    CC_BIN="/usr/bin/cc-connect"
  else
    CC_BIN=$(which cc-connect 2>/dev/null || echo "/usr/bin/cc-connect")
  fi

  write_file "/etc/systemd/system/cc-connect.service" \
    "$(bridge_render_systemd cc-connect.service "$ENV_BLOCK")"
  run_cmd systemctl daemon-reload
  run_cmd systemctl enable cc-connect
}

# ============================================================================
# Upgrade-time config sync (Phase 2)
# ============================================================================

bridge_sync_config() {
  log "Phase 2: cc-connect detected — no per-install artifacts to sync."
  if command -v cc-connect &>/dev/null; then
    local cc_version
    cc_version=$(cc-connect --version 2>/dev/null | head -1 || echo "unknown")
    log "  cc-connect version: $cc_version"
  else
    warn "  cc-connect binary not on PATH"
  fi
  log "  To update upstream:  npm update -g cc-connect"
  log "  User config (never touched):  \$CC_DATA_DIR/config.toml (defaults to \$HOME/.cc-connect/config.toml)"
}

# ============================================================================
# Upgrade-time service refresh (Phase 5)
# ============================================================================

bridge_update_systemd() {
  log "Phase 5: Checking cc-connect.service template..."

  local UNIT_FILE="/etc/systemd/system/cc-connect.service"
  [ -f "$UNIT_FILE" ] || { warn "  $UNIT_FILE does not exist — skipping"; return 0; }

  local CURRENT_ENV
  CURRENT_ENV=$(grep '^Environment=' "$UNIT_FILE" || true)

  local CC_BIN
  CC_BIN=$(which cc-connect 2>/dev/null || echo "/usr/bin/cc-connect")

  # CC_CONNECT_TOKEN lives in the existing unit's env if setup originally
  # set it; mandatory template omits it and _merge_systemd_env_lines
  # preserves host-specific keys.
  local TEMPLATE_ENV="Environment=HOME=$SERVICE_HOME
Environment=PATH=/usr/local/bin:/usr/bin:/bin"

  local MERGED_ENV
  MERGED_ENV=$(_merge_systemd_env_lines "$CURRENT_ENV" "$TEMPLATE_ENV")

  local NEW_UNIT
  NEW_UNIT=$(bridge_render_systemd cc-connect.service "$MERGED_ENV")

  _smart_update_systemd_unit "$UNIT_FILE" "$NEW_UNIT" "cc-connect.service"
}

# bridge_update_launchd: cc-connect doesn't refresh its plist on upgrade
# (no token-merge path to maintain). Leave undefined; the dispatcher's
# bridge_has_hook gate handles the no-op.

# ============================================================================
# Templates: systemd unit + launchd plist
# ============================================================================

bridge_render_systemd() {
  local unit="$1" env_block="$2"
  [ "$unit" = "cc-connect.service" ] || { echo "cc-connect has no unit '$unit'" >&2; return 1; }
  cat <<EOF
[Unit]
Description=cc-connect Chat Bridge (wp-coding-agents)
After=network.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$SITE_PATH
$env_block
ExecStart=$CC_BIN
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
}

bridge_render_launchd() {
  local label="$1"
  [ "$label" = "com.wp.cc-connect" ] || { echo "cc-connect has no label '$label'" >&2; return 1; }
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$label</string>
    <key>ProgramArguments</key>
    <array>
        <string>$CC_BIN</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$SITE_PATH</string>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$CC_DATA_DIR/cc-connect.log</string>
    <key>StandardErrorPath</key>
    <string>$CC_DATA_DIR/cc-connect.error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
EOF
}

# ============================================================================
# Human-facing command accessors
# ============================================================================

bridge_restart_cmd() {
  local env="$1" uid
  uid=$(id -u)
  case "$env" in
    local-launchd)
      echo "launchctl bootout gui/${uid} ~/Library/LaunchAgents/com.wp.cc-connect.plist 2>/dev/null || true; launchctl bootstrap gui/${uid} ~/Library/LaunchAgents/com.wp.cc-connect.plist"
      ;;
    local-manual)
      echo "cd $SITE_PATH && cc-connect"
      ;;
    vps)
      echo "systemctl restart cc-connect"
      ;;
    *)
      echo "bridge_restart_cmd: unknown env '$env'" >&2
      return 1 ;;
  esac
}

bridge_verify_cmd() {
  local env="$1" uid
  uid=$(id -u)
  case "$env" in
    local-launchd) echo "launchctl print gui/${uid}/com.wp.cc-connect | head -20" ;;
    local-manual)  echo "pgrep -fl cc-connect" ;;
    vps)           echo "systemctl status cc-connect" ;;
    *)
      echo "bridge_verify_cmd: unknown env '$env'" >&2
      return 1 ;;
  esac
}

bridge_logs_cmd() {
  echo "tail -f ${CC_DATA_DIR:-$SERVICE_HOME/.cc-connect}/cc-connect.log"
}

bridge_start_hint() {
  local env="$1" uid
  uid=$(id -u)
  case "$env" in
    local-launchd) echo "launchctl kickstart gui/${uid}/com.wp.cc-connect" ;;
    local-manual)  bridge_restart_cmd local-manual ;;
    vps)           echo "systemctl start cc-connect" ;;
    *)
      echo "bridge_start_hint: unknown env '$env'" >&2
      return 1 ;;
  esac
}

bridge_stop_hint() {
  local env="$1" uid
  uid=$(id -u)
  case "$env" in
    local-launchd) echo "launchctl kill SIGTERM gui/${uid}/com.wp.cc-connect" ;;
    vps)           echo "systemctl stop cc-connect" ;;
    local-manual)  ;;
    *)
      echo "bridge_stop_hint: unknown env '$env'" >&2
      return 1 ;;
  esac
}

# ============================================================================
# Summary blocks
# ============================================================================

# cc-connect has no token requirement so bridge_is_ready always returns 0;
# the launchd-setup / vps-setup blocks are never invoked. Intentionally not
# defined.

# Verify-block addendum printed by upgrade.sh after the standard status line.
bridge_verify_extra() {
  echo "cc-connect --version   # binary version"
}
