#!/bin/bash
# Chat bridge: kimaki, cc-connect, telegram — install, config, service setup
#
# Unit-file and plist templates, detection logic, and human-facing command
# accessors all live in lib/chat-bridges.sh (plural). This file is the
# install-time entrypoint that stitches per-install values into the registry.

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/chat-bridges.sh"

install_chat_bridge() {
  if [ "$INSTALL_CHAT" != true ]; then
    log "Phase 9: Skipping chat bridge (--no-chat)"
    return
  fi

  log "Phase 9: Installing chat bridge ($CHAT_BRIDGE)..."

  case "$CHAT_BRIDGE" in
    kimaki)   _install_kimaki ;;
    cc-connect) _install_cc_connect ;;
    telegram) _install_telegram ;;
    *)
      warn "Unknown chat bridge: $CHAT_BRIDGE"
      warn "Supported bridges: kimaki, cc-connect, telegram"
      warn "Skipping chat bridge installation"
      ;;
  esac
}

_install_kimaki() {
  if ! command -v kimaki &> /dev/null || [ "$DRY_RUN" = true ]; then
    run_cmd npm install -g kimaki
  else
    log "Kimaki already installed: $(kimaki --version 2>/dev/null | head -1)"
  fi

  if [ "$LOCAL_MODE" = true ] && [ "$PLATFORM" = "mac" ]; then
    _install_kimaki_launchd
  elif [ "$LOCAL_MODE" = true ]; then
    log "Local mode: Kimaki installed. Run manually with:"
    log "  cd $SITE_PATH && kimaki"
  else
    _install_kimaki_systemd
  fi
}

_install_kimaki_launchd() {
  KIMAKI_PLIST_LABEL="com.wp.kimaki"
  KIMAKI_PLIST_DIR="$HOME/Library/LaunchAgents"
  KIMAKI_PLIST="$KIMAKI_PLIST_DIR/$KIMAKI_PLIST_LABEL.plist"

  if [ "$DRY_RUN" = true ]; then
    KIMAKI_BIN="/opt/homebrew/bin/kimaki"
  else
    KIMAKI_BIN=$(which kimaki 2>/dev/null || echo "/opt/homebrew/bin/kimaki")
  fi

  run_cmd mkdir -p "$KIMAKI_DATA_DIR"
  run_cmd mkdir -p "$KIMAKI_PLIST_DIR"

  write_file "$KIMAKI_PLIST" "$(bridge_render_launchd kimaki "$KIMAKI_PLIST_LABEL")"

  if [ "$DRY_RUN" = false ] && [ -n "$KIMAKI_BOT_TOKEN" ]; then
    launchctl bootout "gui/$(id -u)" "$KIMAKI_PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$KIMAKI_PLIST"
    log "Kimaki launchd service installed and started"
  elif [ "$DRY_RUN" = false ]; then
    log "KIMAKI_BOT_TOKEN not set — service not started"
    log "Run onboarding first, then enable the service:"
    log "  cd $SITE_PATH && kimaki"
    log "  launchctl bootstrap gui/$(id -u) $KIMAKI_PLIST"
  fi

  log "Kimaki service: $KIMAKI_PLIST_LABEL"
  log "  Start:  launchctl kickstart gui/$(id -u)/$KIMAKI_PLIST_LABEL"
  log "  Stop:   launchctl kill SIGTERM gui/$(id -u)/$KIMAKI_PLIST_LABEL"
  log "  Logs:   tail -f $KIMAKI_DATA_DIR/kimaki.log"
}

_install_kimaki_systemd() {
  KIMAKI_CONFIG_DIR="/opt/kimaki-config"
  run_cmd cp -r "$SCRIPT_DIR/kimaki" "$KIMAKI_CONFIG_DIR"
  run_cmd chmod +x "$KIMAKI_CONFIG_DIR/post-upgrade.sh"

  if [ "$DRY_RUN" = true ]; then
    KIMAKI_BIN="/usr/bin/kimaki"
  else
    KIMAKI_BIN=$(which kimaki 2>/dev/null || echo "/usr/bin/kimaki")
  fi

  local KIMAKI_BIN_DIR NODE_BIN_DIR PATH_VALUE
  KIMAKI_BIN_DIR=$(dirname "$KIMAKI_BIN")
  NODE_BIN_DIR=$(_resolve_node_bin_dir "$KIMAKI_BIN")
  PATH_VALUE=$(_compose_path_value "$KIMAKI_BIN_DIR" "$NODE_BIN_DIR" /usr/local/bin /usr/bin /bin)

  local ENV_BLOCK="Environment=HOME=$SERVICE_HOME
Environment=PATH=$PATH_VALUE
Environment=KIMAKI_DATA_DIR=$KIMAKI_DATA_DIR"
  if [ -n "$KIMAKI_BOT_TOKEN" ]; then
    ENV_BLOCK="$ENV_BLOCK
Environment=KIMAKI_BOT_TOKEN=$KIMAKI_BOT_TOKEN"
  fi

  write_file "/etc/systemd/system/kimaki.service" \
    "$(bridge_render_systemd kimaki kimaki.service "$ENV_BLOCK")"
  run_cmd systemctl daemon-reload
  run_cmd systemctl enable kimaki
}

_install_cc_connect() {
  if ! command -v cc-connect &> /dev/null || [ "$DRY_RUN" = true ]; then
    run_cmd npm install -g cc-connect
  else
    log "cc-connect already installed"
  fi

  CC_DATA_DIR="${CC_DATA_DIR:-$SERVICE_HOME/.cc-connect}"

  if [ "$LOCAL_MODE" = true ] && [ "$PLATFORM" = "mac" ]; then
    _install_cc_connect_launchd
  elif [ "$LOCAL_MODE" = true ]; then
    run_cmd mkdir -p "$CC_DATA_DIR"
    _write_cc_config
    log "Local mode: cc-connect installed. Run manually with:"
    log "  cd $SITE_PATH && cc-connect"
  else
    _install_cc_connect_systemd
  fi
}

_write_cc_config() {
  CC_CONFIG_FILE="$CC_DATA_DIR/config.toml"
  if [ "$DRY_RUN" = false ] && [ -f "$CC_CONFIG_FILE" ]; then
    log "cc-connect config already exists — skipping"
    return
  fi

  CC_CONFIG="# cc-connect configuration
# Generated by wp-coding-agents setup

[project]
path = \"$SITE_PATH\"
agent = \"claude\"

[claude]
working_directory = \"$SITE_PATH\""

  write_file "$CC_CONFIG_FILE" "$CC_CONFIG"
  log "Generated cc-connect config at $CC_CONFIG_FILE"
}

_install_cc_connect_launchd() {
  CC_PLIST_LABEL="com.wp.cc-connect"
  CC_PLIST_DIR="$HOME/Library/LaunchAgents"
  CC_PLIST="$CC_PLIST_DIR/$CC_PLIST_LABEL.plist"

  if [ "$DRY_RUN" = true ]; then
    CC_BIN="/opt/homebrew/bin/cc-connect"
  else
    CC_BIN=$(which cc-connect 2>/dev/null || echo "/opt/homebrew/bin/cc-connect")
  fi

  run_cmd mkdir -p "$CC_DATA_DIR"
  run_cmd mkdir -p "$CC_PLIST_DIR"
  _write_cc_config

  write_file "$CC_PLIST" "$(bridge_render_launchd cc-connect "$CC_PLIST_LABEL")"

  if [ "$DRY_RUN" = false ]; then
    launchctl bootout "gui/$(id -u)" "$CC_PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$CC_PLIST"
    log "cc-connect launchd service installed and loaded"
  fi

  log "cc-connect service: $CC_PLIST_LABEL"
  log "  Start:  launchctl kickstart gui/$(id -u)/$CC_PLIST_LABEL"
  log "  Stop:   launchctl kill SIGTERM gui/$(id -u)/$CC_PLIST_LABEL"
  log "  Logs:   tail -f $CC_DATA_DIR/cc-connect.log"
}

_install_cc_connect_systemd() {
  run_cmd mkdir -p "$CC_DATA_DIR"
  _write_cc_config

  local ENV_BLOCK="Environment=HOME=$SERVICE_HOME
Environment=PATH=/usr/local/bin:/usr/bin:/bin"
  if [ -n "${CC_CONNECT_TOKEN:-}" ]; then
    ENV_BLOCK="$ENV_BLOCK
Environment=CC_CONNECT_TOKEN=$CC_CONNECT_TOKEN"
  fi

  if [ "$DRY_RUN" = true ]; then
    CC_BIN="/usr/bin/cc-connect"
  else
    CC_BIN=$(which cc-connect 2>/dev/null || echo "/usr/bin/cc-connect")
  fi

  write_file "/etc/systemd/system/cc-connect.service" \
    "$(bridge_render_systemd cc-connect cc-connect.service "$ENV_BLOCK")"
  run_cmd systemctl daemon-reload
  run_cmd systemctl enable cc-connect
}

_install_telegram() {
  if ! command -v opencode-telegram &> /dev/null || [ "$DRY_RUN" = true ]; then
    run_cmd npm install -g @grinev/opencode-telegram-bot
  else
    log "opencode-telegram already installed: $(opencode-telegram --version 2>/dev/null | head -1)"
  fi

  if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    warn "TELEGRAM_BOT_TOKEN not set — service will fail to start until you add it."
    warn "  Edit $SERVICE_HOME/.config/opencode-telegram-bot/.env after setup."
  fi
  if [ -z "$TELEGRAM_ALLOWED_USER_ID" ]; then
    warn "TELEGRAM_ALLOWED_USER_ID not set — service will fail to start until you add it."
    warn "  Get your ID from @userinfobot on Telegram, then edit the .env file."
  fi

  # Find binaries
  if [ "$DRY_RUN" = true ]; then
    if [ "$LOCAL_MODE" = true ] && [ "$PLATFORM" = "mac" ]; then
      TELEGRAM_BIN="/opt/homebrew/bin/opencode-telegram"
      OPENCODE_BIN="/opt/homebrew/bin/opencode"
    else
      TELEGRAM_BIN="/usr/bin/opencode-telegram"
      OPENCODE_BIN="/usr/bin/opencode"
    fi
  else
    TELEGRAM_BIN=$(which opencode-telegram 2>/dev/null || echo "/usr/bin/opencode-telegram")
    OPENCODE_BIN=$(which opencode 2>/dev/null || echo "/usr/bin/opencode")
  fi

  # opencode-serve env file
  SERVE_ENV_FILE="$SERVICE_HOME/.config/opencode-serve.env"
  run_cmd mkdir -p "$SERVICE_HOME/.config"
  if [ "$DRY_RUN" = true ]; then
    echo -e "${BLUE}[dry-run]${NC} Would write opencode-serve config to $SERVE_ENV_FILE"
  else
    {
      [ -n "$OPENCODE_MODEL" ] && echo "OPENCODE_MODEL=$OPENCODE_MODEL"
      true
    } > "$SERVE_ENV_FILE"
    chmod 600 "$SERVE_ENV_FILE"
    if [ "$LOCAL_MODE" = false ] && [ "$RUN_AS_ROOT" = false ]; then
      chown "$SERVICE_USER:$SERVICE_USER" "$SERVE_ENV_FILE"
    fi
  fi

  # Telegram bot .env file
  TELEGRAM_CONFIG_DIR="$SERVICE_HOME/.config/opencode-telegram-bot"
  run_cmd mkdir -p "$TELEGRAM_CONFIG_DIR"
  if [ "$LOCAL_MODE" = false ] && [ "$RUN_AS_ROOT" = false ]; then
    run_cmd chown -R "$SERVICE_USER:$SERVICE_USER" "$TELEGRAM_CONFIG_DIR"
  fi

  TELEGRAM_ENV_CONTENT="TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_ALLOWED_USER_ID=${TELEGRAM_ALLOWED_USER_ID:-}
OPENCODE_API_URL=http://localhost:4096
OPENCODE_MODEL_PROVIDER=${OPENCODE_MODEL_PROVIDER:-opencode}
OPENCODE_MODEL_ID=${OPENCODE_MODEL_ID:-big-pickle}
LOG_LEVEL=info"

  if [ "$DRY_RUN" = true ]; then
    echo -e "${BLUE}[dry-run]${NC} Would write Telegram bot config to $TELEGRAM_CONFIG_DIR/.env"
  else
    echo "$TELEGRAM_ENV_CONTENT" > "$TELEGRAM_CONFIG_DIR/.env"
    chmod 600 "$TELEGRAM_CONFIG_DIR/.env"
    if [ "$LOCAL_MODE" = false ] && [ "$RUN_AS_ROOT" = false ]; then
      chown "$SERVICE_USER:$SERVICE_USER" "$TELEGRAM_CONFIG_DIR/.env"
    fi
  fi

  if [ "$LOCAL_MODE" = true ] && [ "$PLATFORM" = "mac" ]; then
    _install_telegram_launchd
  elif [ "$LOCAL_MODE" = true ]; then
    log "Local mode: Telegram bot installed. Run manually with:"
    log "  cd $SITE_PATH && opencode serve &"
    log "  opencode-telegram start"
  else
    _install_telegram_systemd
  fi
}

_install_telegram_launchd() {
  SERVE_PLIST_LABEL="com.wp.opencode-serve"
  TELEGRAM_PLIST_LABEL="com.wp.opencode-telegram"
  PLIST_DIR="$HOME/Library/LaunchAgents"
  SERVE_PLIST="$PLIST_DIR/$SERVE_PLIST_LABEL.plist"
  TELEGRAM_PLIST="$PLIST_DIR/$TELEGRAM_PLIST_LABEL.plist"
  TELEGRAM_LOG_DIR="$SERVICE_HOME/.config/opencode-telegram-bot"

  run_cmd mkdir -p "$PLIST_DIR"

  write_file "$SERVE_PLIST" "$(bridge_render_launchd telegram "$SERVE_PLIST_LABEL")"
  write_file "$TELEGRAM_PLIST" "$(bridge_render_launchd telegram "$TELEGRAM_PLIST_LABEL")"

  if [ "$DRY_RUN" = false ] && [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_ALLOWED_USER_ID" ]; then
    launchctl bootout "gui/$(id -u)" "$SERVE_PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$SERVE_PLIST"
    launchctl bootout "gui/$(id -u)" "$TELEGRAM_PLIST" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$TELEGRAM_PLIST"
    log "Telegram bot launchd services installed and started"
  elif [ "$DRY_RUN" = false ]; then
    log "Telegram credentials not set — services not started"
    log "Add tokens to $TELEGRAM_CONFIG_DIR/.env, then re-run setup or bootstrap manually:"
    log "  launchctl bootstrap gui/$(id -u) $SERVE_PLIST"
    log "  launchctl bootstrap gui/$(id -u) $TELEGRAM_PLIST"
  fi

  log "OpenCode serve: $SERVE_PLIST_LABEL"
  log "Telegram bot:   $TELEGRAM_PLIST_LABEL"
  log "  Start:  launchctl kickstart gui/$(id -u)/$SERVE_PLIST_LABEL"
  log "          launchctl kickstart gui/$(id -u)/$TELEGRAM_PLIST_LABEL"
  log "  Stop:   launchctl kill SIGTERM gui/$(id -u)/$SERVE_PLIST_LABEL"
  log "          launchctl kill SIGTERM gui/$(id -u)/$TELEGRAM_PLIST_LABEL"
  log "  Logs:   tail -f $TELEGRAM_LOG_DIR/opencode-serve.log"
  log "          tail -f $TELEGRAM_LOG_DIR/opencode-telegram.log"
}

_install_telegram_systemd() {
  local ENV_BLOCK="Environment=HOME=$SERVICE_HOME
Environment=PATH=/usr/local/bin:/usr/bin:/bin"

  write_file "/etc/systemd/system/opencode-serve.service" \
    "$(bridge_render_systemd telegram opencode-serve.service "$ENV_BLOCK")"
  run_cmd systemctl daemon-reload
  run_cmd systemctl enable opencode-serve

  write_file "/etc/systemd/system/opencode-telegram.service" \
    "$(bridge_render_systemd telegram opencode-telegram.service "$ENV_BLOCK")"
  run_cmd systemctl daemon-reload
  run_cmd systemctl enable opencode-telegram
}
